/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class view_form_login extends javax.swing.JFrame {

    String user, password;

    public view_form_login() {
        initComponents();
        setLocationRelativeTo(this);
        getPasswordField_Password();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Username = new javax.swing.JTextField();
        PasswordField_Password = new javax.swing.JPasswordField();
        Button_Login = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextField_Username.setMinimumSize(new java.awt.Dimension(5, 25));
        TextField_Username.setPreferredSize(new java.awt.Dimension(5, 25));
        TextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 160, 30));

        PasswordField_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PasswordField_Password.setMinimumSize(new java.awt.Dimension(5, 25));
        getContentPane().add(PasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 160, 30));

        Button_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_login.png"))); // NOI18N
        Button_Login.setBorderPainted(false);
        Button_Login.setContentAreaFilled(false);
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 100, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/form_login.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1000, 600));
        Background.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_UsernameActionPerformed

    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
        try {
            user = TextField_Username.getText();
            password = getPasswordField_Password();
            if (user.equalsIgnoreCase("admin") && password.equalsIgnoreCase("admin")) {
                new view_form_home_admin().setVisible(true);
                dispose();
            } else if (user.equalsIgnoreCase("manager") && password.equalsIgnoreCase("manager")) {
                new view_form_home_Manager().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Password atau Username anda salah!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tidak Adak Koneksi");
        }

    }//GEN-LAST:event_Button_LoginActionPerformed

    public String getUser() {
        return user;
    }

    public JButton getButton_Login() {
        return Button_Login;
    }

    public String getPasswordField_Password() {
        String pass = "";
        char passArray[] = this.PasswordField_Password.getPassword();
        for (int i = 0; i < passArray.length; i++) {
            pass += passArray[i];
        }

        return pass;
    }

    public JTextField getTextField_Username() {
        return TextField_Username;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Login;
    private javax.swing.JPasswordField PasswordField_Password;
    private javax.swing.JTextField TextField_Username;
    // End of variables declaration//GEN-END:variables
}
