/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Bagas
 */
public class view_home extends javax.swing.JFrame {

    /**
     * Creates new form view_home
     */
    public view_home() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void DaftarListener(ActionListener l) {
        this.Button_Daftar.addActionListener(l);
    }

    public void LoginHomeListener(ActionListener l) {
        this.Button_login.addActionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Daftar = new javax.swing.JButton();
        Button_login = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Daftar.setText("Daftar");
        getContentPane().add(Button_Daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        Button_login.setText("Login");
        getContentPane().add(Button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/form_home_admin.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Daftar;
    private javax.swing.JButton Button_login;
    // End of variables declaration//GEN-END:variables
}
