/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JYearChooser;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bagas
 */
public class view_dialog_kelolaBuku extends java.awt.Dialog {

    /**
     * Creates new form dialog_kelolaBuku
     */
    public view_dialog_kelolaBuku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_Penerbit = new javax.swing.JTextField();
        TextField_KodeBuku = new javax.swing.JTextField();
        TextField_JudulBuku = new javax.swing.JTextField();
        TextField_Pengarang = new javax.swing.JTextField();
        Button_Perbarui = new javax.swing.JButton();
        Button_Simpan = new javax.swing.JButton();
        Button_Hapus = new javax.swing.JButton();
        Button_Segarkan = new javax.swing.JButton();
        YearChooser_TahunTerbitBuku = new com.toedter.calendar.JYearChooser();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_KategoriBuku = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextField_Stok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_DataBuku = new javax.swing.JTable();
        Button_pilih = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setResizable(false);
        setSize(new java.awt.Dimension(900, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kode Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Judul");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Pengarang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Penerbit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        TextField_Penerbit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_PenerbitKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_Penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        TextField_KodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_KodeBukuActionPerformed(evt);
            }
        });
        TextField_KodeBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_KodeBukuKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_KodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, -1));

        TextField_JudulBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_JudulBukuKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_JudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 160, -1));

        TextField_Pengarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_PengarangKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_Pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, -1));

        Button_Perbarui.setText("Perbarui");
        jPanel1.add(Button_Perbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Button_Simpan.setText("Simpan");
        Button_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        Button_Hapus.setText("Hapus");
        jPanel1.add(Button_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        Button_Segarkan.setText("Segarkan");
        jPanel1.add(Button_Segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        jPanel1.add(YearChooser_TahunTerbitBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Kategori");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel1.add(ComboBox_KategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Stok");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tahun Terbit");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        TextField_Stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_StokKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_Stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 320));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Table_DataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "KODE BUKU", "JUDUL BUKU", "PENGARANG", "PENERBIT", "TAHUN TERBIT", "KATEGORI", "STOK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table_DataBuku);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        Button_pilih.setText("Pilih");
        jPanel2.add(Button_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 500, 320));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_kelolaBuku.png"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTabel(DefaultTableModel tabel) {
        this.Table_DataBuku.setModel(tabel);
    }

    public int getSelectedRow() {
        return Table_DataBuku.getSelectedRow();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.Table_DataBuku.getValueAt(baris, kolom);
    }

    public void simpanKelolaBukuListener(ActionListener l) {
        this.Button_Simpan.addActionListener(l);
    }

    public void segarkanKelolaBukuListener(ActionListener l) {
        this.Button_Segarkan.addActionListener(l);
    }

    public void hapusKelolaBukuListener(ActionListener l) {
        this.Button_Hapus.addActionListener(l);
    }

    public void perbaruiKelolaBukuListener(ActionListener l) {
        this.Button_Perbarui.addActionListener(l);
    }

    public void pilihKelolaBukuListener(ActionListener l) {
        this.Button_pilih.addActionListener(l);
    }

    public String getTextField_Penerbit() {
        return TextField_Penerbit.getText();
    }

    public String getTextField_KodeBuku() {
        return TextField_KodeBuku.getText();
    }

    public String getTextField_JudulBuku() {
        return TextField_JudulBuku.getText();
    }

    public String getTextField_Pengarang() {
        return TextField_Pengarang.getText();
    }

    public String getTextField_Stok() {
        return TextField_Stok.getText();
    }

    public String getYearChooser_TahunTerbitBuku() {
        int year = YearChooser_TahunTerbitBuku.getValue();
        return String.valueOf(year);
    }

    public void setTextField_JudulBuku(String value) {
        this.TextField_JudulBuku.setText(value);
    }

    public void setTextField_KodeBuku(String value) {
        this.TextField_KodeBuku.setText(value);
    }

    public void setTextField_Penerbit(String value) {
        this.TextField_Penerbit.setText(value);
    }

    public void setTextField_Pengarang(String value) {
        this.TextField_Pengarang.setText(value);
    }

    public void setTextField_Stok(String value) {
        this.TextField_Stok.setText(value);
    }

    public void setYearChooser_TahunTerbitBuku(String value) {
        this.YearChooser_TahunTerbitBuku.setYear(Integer.parseInt(value));
    }

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void setComboBox_KategoriBuku(String[] ComboBox_KategoriBuku) {
        for (String a : ComboBox_KategoriBuku) {
            this.ComboBox_KategoriBuku.addItem(a);
        }
    }

    public String getComboBox_KategoriBuku() {
        return ComboBox_KategoriBuku.getSelectedItem().toString();
    }


    private void TextField_KodeBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_KodeBukuKeyTyped

    }//GEN-LAST:event_TextField_KodeBukuKeyTyped

    private void TextField_JudulBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_JudulBukuKeyTyped

    }//GEN-LAST:event_TextField_JudulBukuKeyTyped

    private void TextField_PengarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_PengarangKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PengarangKeyTyped

    private void TextField_PenerbitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_PenerbitKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TextField_PenerbitKeyTyped

    private void TextField_StokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_StokKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TextField_StokKeyTyped

    private void TextField_KodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_KodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_KodeBukuActionPerformed

    private void Button_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                view_dialog_kelolaBuku dialog = new view_dialog_kelolaBuku(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Hapus;
    private javax.swing.JButton Button_Perbarui;
    private javax.swing.JButton Button_Segarkan;
    private javax.swing.JButton Button_Simpan;
    private javax.swing.JButton Button_pilih;
    private javax.swing.JComboBox<String> ComboBox_KategoriBuku;
    private javax.swing.JTable Table_DataBuku;
    private javax.swing.JTextField TextField_JudulBuku;
    private javax.swing.JTextField TextField_KodeBuku;
    private javax.swing.JTextField TextField_Penerbit;
    private javax.swing.JTextField TextField_Pengarang;
    private javax.swing.JTextField TextField_Stok;
    private com.toedter.calendar.JYearChooser YearChooser_TahunTerbitBuku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
