/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bagas
 */
public class view_dialog_kelolaPeminjaman extends java.awt.Dialog {

    String tanggalPinjam, tanggalBalik;

    /**
     * Creates new form dialog_kelolaBuku
     */
    public view_dialog_kelolaPeminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public void buttonEdit(boolean status) {
        this.Button_Perbarui.setEnabled(status);
    }

    public void buttonSimpan(boolean status) {
        this.Button_Simpan.setEnabled(status);
    }

    public void setTabel(DefaultTableModel tabel) {
        this.Table_DataPeminjaman.setModel(tabel);
    }

    public int getSelectedRow() {
        return Table_DataPeminjaman.getSelectedRow();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.Table_DataPeminjaman.getValueAt(baris, kolom);
    }

    public void simpanKelolaPeminjamanListener(ActionListener l) {
        this.Button_Simpan.addActionListener(l);
    }

    public void segarkanKelolaPeminjamanListener(ActionListener l) {
        this.Button_Segarkan.addActionListener(l);
    }

    public void hapusKelolaPeminjamanListener(ActionListener l) {
        this.Button_Hapus.addActionListener(l);
    }

    public void perbaruiKelolaPeminjamanListener(ActionListener l) {
        this.Button_Perbarui.addActionListener(l);
    }

    public void pilihKelolaPeminjamanListener(ActionListener l) {
        this.Button_pilih.addActionListener(l);
    }

    public void setComboBox_Statuspinjam(String[] ComboBox_KategoriBuku) {
        for (String a : ComboBox_KategoriBuku) {
            this.ComboBox_StatusPinjam.addItem(a);
        }
    }

    public String getComboBox_Statuspinjam() {
        return ComboBox_StatusPinjam.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_NIM = new javax.swing.JTextField();
        TextField_kodeBuku = new javax.swing.JTextField();
        Button_Perbarui = new javax.swing.JButton();
        Button_Simpan = new javax.swing.JButton();
        Button_Hapus = new javax.swing.JButton();
        Button_Segarkan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DateChooser_TanggalPinjam = new com.toedter.calendar.JDateChooser();
        DateChooser_TanggalPengembalian = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        ComboBox_StatusPinjam = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_DataPeminjaman = new javax.swing.JTable();
        Button_pilih = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setResizable(false);
        setSize(new java.awt.Dimension(900, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NIM ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("kode Buku");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Pinjam");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        TextField_NIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NIMKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, -1));

        TextField_kodeBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_kodeBukuKeyTyped(evt);
            }
        });
        jPanel1.add(TextField_kodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        Button_Perbarui.setText("Perbarui");
        jPanel1.add(Button_Perbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Button_Simpan.setText("Simpan");
        jPanel1.add(Button_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        Button_Hapus.setText("Hapus");
        jPanel1.add(Button_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        Button_Segarkan.setText("Segarkan");
        jPanel1.add(Button_Segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Pengembalian");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        DateChooser_TanggalPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooser_TanggalPinjamPropertyChange(evt);
            }
        });
        jPanel1.add(DateChooser_TanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        DateChooser_TanggalPengembalian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooser_TanggalPengembalianPropertyChange(evt);
            }
        });
        jPanel1.add(DateChooser_TanggalPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, -1));

        jLabel1.setText("Status");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jPanel1.add(ComboBox_StatusPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 320));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Table_DataPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIM", "NAMA", "FAKUTAS", "ID BUKU", "JUDUL BUKU", "KATEGORI", "TANGGAL PINJAM", "TANGGAL PENGEMBALIAN", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_DataPeminjaman.setPreferredSize(new java.awt.Dimension(1300, 470));
        jScrollPane2.setViewportView(Table_DataPeminjaman);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        Button_pilih.setText("Pilih");
        jPanel2.add(Button_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 500, 320));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_kelolaPeminjaman.png"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextField_NIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NIMKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TextField_NIMKeyTyped

    private void TextField_kodeBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_kodeBukuKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TextField_kodeBukuKeyTyped

    private void DateChooser_TanggalPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooser_TanggalPinjamPropertyChange
        if (DateChooser_TanggalPinjam.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            tanggalPinjam = sdf.format(DateChooser_TanggalPinjam.getDate());
            System.out.println(tanggalPinjam);
    }//GEN-LAST:event_DateChooser_TanggalPinjamPropertyChange
    }

    private void DateChooser_TanggalPengembalianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooser_TanggalPengembalianPropertyChange
        if (DateChooser_TanggalPengembalian.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            tanggalBalik = sdf.format(DateChooser_TanggalPengembalian.getDate());
            System.out.println(tanggalBalik);
        }
    }//GEN-LAST:event_DateChooser_TanggalPengembalianPropertyChange

    public String getTanggalPinjam() {
        return tanggalPinjam;
    }

    public void setTanggalPinjam(String tanggalPinjam) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse(tanggalPinjam);
        this.DateChooser_TanggalPinjam.setDate(date);
    }

    public String getTanggalPengembalian() {
        return tanggalBalik;
    }

    public void setTanggalPengembalian(String tanggalBalik) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse(tanggalBalik);
        this.DateChooser_TanggalPengembalian.setDate(date);
    }

    public String getTextField_NIM() {
        return TextField_NIM.getText();
    }

    public void setTextField_NIM(String TextField_NIM) {
        this.TextField_NIM.setText(TextField_NIM);;
    }

    public String getTextField_kodeBuku() {
        return TextField_kodeBuku.getText();
    }

    public void setTextField_kodeBuku(String TextField_kodeBuku) {
        this.TextField_kodeBuku.setText(TextField_kodeBuku);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Hapus;
    private javax.swing.JButton Button_Perbarui;
    private javax.swing.JButton Button_Segarkan;
    private javax.swing.JButton Button_Simpan;
    private javax.swing.JButton Button_pilih;
    private javax.swing.JComboBox<String> ComboBox_StatusPinjam;
    private com.toedter.calendar.JDateChooser DateChooser_TanggalPengembalian;
    private com.toedter.calendar.JDateChooser DateChooser_TanggalPinjam;
    private javax.swing.JTable Table_DataPeminjaman;
    private javax.swing.JTextField TextField_NIM;
    private javax.swing.JTextField TextField_kodeBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
